---

    on:
      push:
    
    jobs:
      test:
        runs-on: ubuntu-latest
        name: just test debug action
        steps:
          - uses: Shiny-Kn/action-debug@main
        #   - name: Checkout
        #     uses: actions/checkout@v4
        #     with:
        #       fetch-depth: 1
        #   - uses: ./